# Generated by Django 5.1.4 on 2025-01-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogisNews',
            fields=[
                ('idNews', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
            ],
        ),
    ]
