# Generated by Django 5.1.4 on 2025-01-16 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisnews',
            name='nome',
            field=models.CharField(default='sem nome', max_length=255),
            preserve_default=False,
        ),
    ]
