# Generated by Django 5.1.4 on 2025-01-27 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_itemcarrinho'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemCarrinho',
        ),
    ]
