# Generated by Django 5.1.4 on 2025-01-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contato'),
    ]

    operations = [
        migrations.CreateModel(
            name='JogoHome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(upload_to='jogos_home/')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(choices=[('nintendo', 'Nintendo'), ('playstation', 'PlayStation'), ('pc', 'PC')], max_length=20)),
                ('eh_lancamento', models.BooleanField(default=False)),
            ],
        ),
    ]
